# -*- coding: utf-8 -*-
"""Data_Preparation_Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TycOgM2Ekc1mf8D1_qk14gO5x4FYrQS1
"""

# data_preparation_modelling.py

import pandas as pd

# Load datasets
df_precip = pd.read_csv("CHIRPS_Monthly_Prairies_1982_2022.csv")
df_evap = pd.read_csv("ERA5_Evapotranspiration_Prairies_1982_2022.csv")
df_pdsi = pd.read_csv("PDSI_TerraClimate_Prairies_1982_2022.csv")

# Merge datasets on 'year' and 'month'
df_merged = df_precip.merge(df_evap, on=["year", "month"])
df_merged = df_merged.merge(df_pdsi, on=["year", "month"])

# Normalize PDSI values (MANDATORY STEP — brings values to ~[-4, 4] range)
df_merged["pdsi"] = df_merged["pdsi"] / 100

# Generate binary drought label (1 = drought, 0 = no drought)
df_merged["drought_label"] = df_merged["pdsi"].apply(lambda x: 1 if x < -0.5 else 0)

# Output basic stats
print("Merged dataset shape:", df_merged.shape)
print("\nDrought Label Counts:")
print(df_merged["drought_label"].value_counts())

print("\nDrought Label Percentage:")
print(df_merged["drought_label"].value_counts(normalize=True) * 100)

# Save preprocessed dataset for ML use
df_merged.to_csv("prepared_drought_dataset.csv", index=False)