# -*- coding: utf-8 -*-
"""Data_Preparation_Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RKPj0M1HHmI_xH9W-GlUtZ3BZ2QefA08

data_preparation.py

Description:
This script performs all data preparation steps required for model training.
It loads raw monthly climate datasets (precipitation, evapotranspiration, and PDSI),
merges them into a single DataFrame, scales the PDSI values, creates a binary drought label,
splits the data into training and test sets with stratification, and standardizes the predictor variables.
The resulting X_train_scaled, X_test_scaled, y_train, and y_test arrays are ready to be used
in downstream modeling workflows.
"
"""

import pandas as pd

#Load raw datasets

df_precip = pd.read_csv("CHIRPS_Monthly_Prairies_2012_2022.csv")
df_evap = pd.read_csv("ERA5_Evapotranspiration_Prairies_2012_2022.csv")
df_pdsi = pd.read_csv("PDSI_TerraClimate_Prairies_2012_2022.csv")

#Merge datasets

df_merged = df_precip.merge(df_evap, on=["year", "month"])
df_merged = df_merged.merge(df_pdsi, on=["year", "month"])

#Scale PDSI values:

df_merged["pdsi"] = df_merged["pdsi"] / 100

#Create drought label:

df_merged["drought_label"] = df_merged["pdsi"].apply(lambda x: 1 if x < -0.5 else 0)

#Select predictors and target:

X = df_merged[["mean_precip_mm", "evap_mm"]]
y = df_merged["drought_label"]

#Train-test split:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

#Standardize predictors

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Training set shape:", X_train.shape)
print("Test set shape:", X_test.shape)
print("Training labels distribution:\n", y_train.value_counts())
print("Test labels distribution:\n", y_test.value_counts())