# -*- coding: utf-8 -*-
"""data_preparation_modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Wyg2lQw7GtixOvuKomJzeEQoStE0vIB
"""

"""
Data Preparation and Drought Labeling Script
--------------------------------------------
This script merges three climate datasets (precipitation, evapotranspiration, and PDSI),
normalizes the PDSI values, generates a binary drought label, and outputs a merged dataset
for use in machine learning models.

Drought Label Rule:
- Drought (label=1) if normalized PDSI < -0.5
- No Drought (label=0) otherwise

Output: prepared_drought_dataset.csv
"""

import pandas as pd

# Load datasets
df_precip = pd.read_csv("CHIRPS_Monthly_Prairies_1982_2022.csv")
df_evap = pd.read_csv("ERA5_Evapotranspiration_Prairies_1982_2022.csv")
df_pdsi = pd.read_csv("PDSI_TerraClimate_Prairies_1982_2022.csv")

# Merge datasets on 'year' and 'month'
df_merged = df_precip.merge(df_evap, on=["year", "month"])
df_merged = df_merged.merge(df_pdsi, on=["year", "month"])

# Normalize PDSI values (MANDATORY step)
df_merged["pdsi"] = df_merged["pdsi"] / 100  # Scales values to ~[-4, 4]

# Generate binary drought label
df_merged["drought_label"] = df_merged["pdsi"].apply(lambda x: 1 if x < -0.5 else 0)

# Output summary statistics
print("Merged dataset shape:", df_merged.shape)
print("\nDrought Label Counts:")
print(df_merged["drought_label"].value_counts())

print("\nDrought Label Percentage:")
print(df_merged["drought_label"].value_counts(normalize=True) * 100)

# Save the processed dataset
df_merged.to_csv("prepared_drought_dataset.csv", index=False)
print("\nSaved to 'prepared_drought_dataset.csv'")